[general]
import = [
		"~/.config/alacritty/themes/gruvbox-dark.toml"
]

# [terminal.shell]
# program = "/usr/bin/tmux"
# args = ["new-session", "-A", "-s", "main"]

[env]
TERM = "xterm-256color"

[window]
opacity = 1
padding.x = 0
padding.y = 0

[font]
size = 11

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[bell]
command = { program = "paplay", args = ["/home/ming/media/notification-sounds/wooden-fish.mp3"] }
